name: CI

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            parser/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: yarn

      - run: yarn prettier --check .

      - run: cd parser && cargo clippy -- -D warnings

      - run: cd parser && cargo fmt -- --check

      - run: |
          yarn generate:licenses
          git diff --exit-code

      - run: yarn build

      - run: yarn lint --no-fix

      - run: yarn test
