name: CI

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - run: yarn

      - run: yarn prettier --check .

      - run: yarn lint --no-fix

      - run: yarn build

      - run: yarn test
